const chapman = [

   ["Channel Islands", "CHI"],
   ["England", "ENG"],
   ["Ireland", "IRL"],
   ["Scotland", "SCT"],
   ["Wales", "WLS"],
   ["All Countries", "ALL"],
   ["Alderney", "ALD"],
   ["Guernsey", "GSY"],
   ["Jersey", "JSY"],
   ["Sark", "SRK"],
   ["Avon", "AVN"],
   ["Bedfordshire", "BDF"],
   ["Berkshire", "BRK"],
   ["Buckinghamshire", "BKM"],
   ["Cambridgeshire", "CAM"],
   ["Cheshire", "CHS"],
   ["Cleveland", "CLV"],
   ["Cornwall", "CON"],
   ["Cumberland", "CUL"],
   ["Cumbria", "CMA"],
   ["Derbyshire", "DBY"],
   ["Devon", "DEV"],
   ["Dorset", "DOR"],
   ["Durham", "DUR"],
   ["East Riding of Yorkshire", "ERY"],
   ["East Sussex", "SXE"],
   ["Essex", "ESS"],
   ["Gloucestershire", "GLS"],
   ["Greater Manchester", "GTM"],
   ["Hampshire", "HAM"],
   ["Hereford & Worcester", "HWR"],
   ["Herefordshire", "HEF"],
   ["Hertfordshire", "HRT"],
   ["Humberside", "HUM"],
   ["Huntingdonshire", "HUN"],
   ["Isle of Man", "IOM"],
   ["Isle of Wight", "IOW"],
   ["Kent", "KEN"],
   ["Lancashire", "LAN"],
   ["Leicestershire", "LEI"],
   ["Lincolnshire", "LIN"],
   ["London", "LND"],
   ["Merseyside", "MSY"],
   ["Middlesex", "MDX"],
   ["Norfolk", "NFK"],
   ["North Riding of Yorkshire", "NRY"],
   ["North Yorkshire", "NYK"],
   ["Northamptonshire", "NTH"],
   ["Northumberland", "NBL"],
   ["Nottinghamshire", "NTT"],
   ["Oxfordshire", "OXF"],
   ["Rutland", "RUT"],
   ["Rutlandshire", "RUT"],
   ["Shropshire", "SAL"],
   ["Somerset", "SOM"],
   ["South Yorkshire", "SYK"],
   ["Staffordshire", "STS"],
   ["Suffolk", "SFK"],
   ["Surrey", "SRY"],
   ["Sussex", "SSX"],
   ["Tyne & Wear", "TWR"],
   ["Warwickshire", "WAR"],
   ["West Midlands", "WMD"],
   ["West Riding of Yorkshire", "WRY"],
   ["West Sussex", "SXW"],
   ["West Yorkshire", "WYK"],
   ["Westmorland", "WES"],
   ["Wiltshire", "WIL"],
   ["Worcestershire", "WOR"],
   ["Yorkshire", "YKS"],
   ["Yorkshire, East Riding", "ERY"],
   ["Yorkshire, North Riding", "NRY"],
   ["Yorkshire, West Riding", "WRY"],
   ["Carlow", "CAR"],
   ["Cavan", "CAV"],
   ["Clare", "CLA"],
   ["Cork", "COR"],
   ["Donegal", "DON"],
   ["Dublin", "DUB"],
   ["Galway", "GAL"],
   ["Kerry", "KER"],
   ["Kildare", "KID"],
   ["Kilkenny", "KIK"],
   ["Laois", "LEX"],
   ["Leitrim", "LET"],
   ["Leix", "LEX"],
   ["Queen's", "LEX"],
   ["Limerick", "LIM"],
   ["Longford", "LOG"],
   ["Louth", "LOU"],
   ["Mayo", "MAY"],
   ["Meath", "MEA"],
   ["Monaghan", "MOG"],
   ["Offaly", "OFF"],
   ["King's", "OFF"],
   ["Roscommon", "ROS"],
   ["Sligo", "SLI"],
   ["Tipperary", "TIP"],
   ["Waterford", "WAT"],
   ["Westmeath", "WEM"],
   ["Wexford", "WEX"],
   ["Wicklow", "WIC"],
   ["Antrim", "ANT"],
   ["Armagh", "ARM"],
   ["Derry", "LDY"],
   ["Down", "DOW"],
   ["Fermanagh", "FER"],
   ["Londonderry", "LDY"],
   ["Tyrone", "TYR"],
   ["Aberdeenshire", "ABD"],
   ["Angus", "ANS"],
   ["Argyllshire", "ARL"],
   ["Arran", "BUT"],
   ["Ayrshire", "AYR"],
   ["Banffshire", "BAN"],
   ["Berwickshire", "BEW"],
   ["Borders", "BOR"],
   ["Bute", "BUT"],
   ["Buteshire", "BUT"],
   ["Caithness", "CAI"],
   ["Caithness-shire", "CAI"],
   ["Central Region", "CEN"],
   ["Central", "CEN"],
   ["Clackmannanshire", "CLK"],
   ["Dumfries & Galloway", "DGY"],
   ["Dumfriesshire", "DFS"],
   ["Dunbartonshire", "DNB"],
   ["East Lothian", "ELN"],
   ["Edinburgh", "MLN"],
   ["Edinburghshire", "MLN"],
   ["Elgin", "MOR"],
   ["Elginshire", "MOR"],
   ["Fife", "FIF"],
   ["Forfar", "ANS"],
   ["Forfarshire", "ANS"],
   ["Grampian", "GMP"],
   ["Haddington", "ELN"],
   ["Haddingtonshire", "ELN"],
   ["Highland", "HLD"],
   ["Inverness-shire", "INV"],
   ["Islay", "ARL"],
   ["Jura", "ARL"],
   ["Kincardineshire", "KCD"],
   ["Kinross-shire", "KRS"],
   ["Kirkcudbrightshire", "KKD"],
   ["Lanarkshire", "LKS"],
   ["Lewis", "INV"],
   ["Lewis", "ROC"],
   ["Linlithgow", "WLN"],
   ["Linlithgowshire", "WLN"],
   ["Lothian", "LTN"],
   ["Mearns", "KCD"],
   ["Midlothian", "MLN"],
   ["Moray", "MOR"],
   ["Mull", "ARL"],
   ["Nairnshire", "NAI"],
   ["North Uist", "INV"],
   ["Orkney Isles", "OKI"],
   ["Orkney", "OKI"],
   ["Peeblesshire", "PEE"],
   ["Perthshire", "PER"],
   ["Renfrewshire", "RFW"],
   ["Ross & Cromarty", "ROC"],
   ["Roxburghshire", "ROX"],
   ["Scilly Isles", "CON"],
   ["Selkirkshire", "SEL"],
   ["Shetland Isles", "SHI"],
   ["Shetland", "SHI"],
   ["Skye", "INV"],
   ["South Uist", "INV"],
   ["Stirlingshire", "STI"],
   ["Strathclyde", "STD"],
   ["Sutherland", "SUT"],
   ["Tayside", "TAY"],
   ["West Galloway", "WIG"],
   ["West Lothian", "WLN"],
   ["Western Isles", "WIS"],
   ["Wigtownshire", "WIG"],
   ["Zetland", "SHI"],
   ["Anglesey", "AGY"],
   ["Breconshire", "BRE"],
   ["Caernavonshire", "CAE"],
   ["Caernarfonshire", "CAE"],
   ["Cardiganshire", "CGN"],
   ["Carmarthenshire", "CMN"],
   ["Clwyd", "CWD"],
   ["Denbighshire", "DEN"],
   ["Dyfed", "DFD"],
   ["Flint", "FLN"],
   ["Flintshire", "FLN"],
   ["Glamorganshire", "GLA"],
   ["Glamorgan", "GLA"],
   ["Gwent", "GNT"],
   ["Gwynedd", "GWN"],
   ["Merionethshire", "MER"],
   ["Mid Glamorgan", "MGM"],
   ["Monmouthshire", "MON"],
   ["Montgomeryshire", "MGY"],
   ["Pembrokeshire", "PEM"],
   ["Powys", "POW"],
   ["Radnorshire", "RAD"],
   ["South Glamorgan", "SGM"],
   ["West Glamorgan", "WGM"],

];
