module.exports = [

  ["Aruba", "ABW"],
  ["Afghanistan", "AFG"],
  ["Angola", "AGO"],
  ["Anguilla", "AIA"],
  ["Aland Islands", "ALA"],
  ["Albania", "ALB"],
  ["Andorra", "AND"],
  ["Netherlands Antilles", "ANT"],
  ["United Arab Emirates", "ARE"],
  ["Argentina", "ARG"],
  ["Armenia", "ARM"],
  ["American Samoa", "ASM"],
  ["Australia", "AU"],
  ["Australia", "AUS"],
  ["Austria", "AUT"],
  ["Azerbaijan", "AZE"],
  ["Baden", "BAD"],
  ["Bavaria", "BAV"],
  ["Burundi", "BDI"],
  ["Belgium", "BEL"],
  ["Benin", "BEN"],
  ["Bonaire, Sint Eustatius and Saba", "BES"],
  ["Burkina Faso", "BFA"],
  ["Bangladesh", "BGD"],
  ["Bulgaria", "BGR"],
  ["Republic of Bulgaria", "BGR"],
  ["Bahrain", "BHR"],
  ["Bosnia and Herzegovina", "BIH"],
  ["Saint Barthelemy", "BLM"],
  ["Belarus", "BLR"],
  ["Bolivia", "BOL"],
  ["Brazil", "BRA"],
  ["Bremen", "BRE"],
  ["Brunei Darussalam", "BRN"],
  ["Bhutan", "BTN"],
  ["Botswana", "BWA"],
  ["Central African Republic", "CAF"],
  ["Canada", "CAN"],
  ["Cocos Islands", "CCK"],
  ["Keeling Islands", "CCK"],
  ["Switzerland", "CHE"],
  ["Chile", "CHL"],
  ["China", "CHN"],
  ["People's Republic of China", "CHN"],
  ["Côte d'Ivoire", "CIV"],
  ["Cameroon", "CMR"],
  ["Democratic Republic of Congo", "COD"],
  ["Congo", "COG"],
  ["Cook Islands", "COK"],
  ["Colombia", "COL"],
  ["Comoros", "COM"],
  ["Cape Verde", "CPV"],
  ["Cuba", "CUB"],
  ["Curaçao", "CUW"],
  ["Christmas Island", "CXR"],
  ["Cyprus", "CYP"],
  ["Czech Republic", "CZE"],
  ["Czechia", "CZE"],
  ["Germany", "DEU"],
  ["Djibouti", "DJI"],
  ["Dominica", "DMA"],
  ["Denmark", "DNK"],
  ["Dominican Republic", "DOM"],
  ["Algeria", "DZA"],
  ["Ecuador", "ECU"],
  ["Egypt", "EGY"],
  ["England", "ENG"],
  ["Eritrea", "ERI"],
  ["Western Sahara", "ESH"],
  ["Spain", "ESP"],
  ["Estonia", "EST"],
  ["Ethiopia", "ETH"],
  ["Finland", "FIN"],
  ["Fiji", "FJI"],
  ["Falkland Islands", "FLK"],
  ["Malvinas", "FLK"],
  ["France", "FRA"],
  ["Faroe Islands", "FRO"],
  ["Micronesia", "FSM"],
  ["Gabon", "GAB"],
  ["United Kingdom", "GBR"],
  ["Great Britain", "GBR"],
  ["Georgia", "GEO"],
  ["Guernsey", "GGY"],
  ["Ghana", "GHA"],
  ["Gibraltar", "GIB"],
  ["Guinea", "GIN"],
  ["Guadeloupe", "GLP"],
  ["Gambia", "GMB"],
  ["Guinea-Bissau", "GNB"],
  ["Equatorial Guinea", "GNQ"],
  ["Greece", "GRC"],
  ["Grenada", "GRD"],
  ["Greenland", "GRL"],
  ["Guatemala", "GTM"],
  ["French Guiana", "GUF"],
  ["Guyana", "GUY"],
  ["Hanover", "HAN"],
  ["Hong Kong", "HKG"],
  ["Honduras", "HND"],
  ["Croatia", "HRV"],
  ["Haiti", "HTI"],
  ["Hungary", "HUN"],
  ["Indonesia", "IDN"],
  ["Isle of Man", "IMN"],
  ["India", "IND"],
  ["British Indian Ocean Territory", "IOT"],
  ["Ireland", "IRL"],
  ["Irish Free State", "IRL"],
  ["S Ireland", "IRL"],
  ["So Ireland", "IRL"],
  ["Southern Ireland", "IRL"],
  ["Iran", "IRN"],
  ["Islamic Republic of Iran", "IRN"],
  ["Iraq", "IRQ"],
  ["Iceland", "ISL"],
  ["Israel", "ISR"],
  ["Italy", "ITA"],
  ["Jamaica", "JAM"],
  ["Jersey", "JEY"],
  ["Jordan", "JOR"],
  ["Japan", "JPN"],
  ["Kazakhstan", "KAZ"],
  ["Kenya", "KEN"],
  ["Kyrgyzstan", "KGZ"],
  ["Cambodia", "KHM"],
  ["Kiribati", "KIR"],
  ["Saint Kitts and Nevis", "KNA"],
  ["Republic of Korea", "KOR"],
  ["South Korea", "KOR"],
  ["Korea", "KOREA"],
  ["Kuwait", "KWT"],
  ["Laos", "LAO"],
  ["Lao People's Democratic Republic", "LAO"],
  ["Lebanon", "LBN"],
  ["Liberia", "LBR"],
  ["Libyan Arab Jamahiriya", "LBY"],
  ["Saint Lucia", "LCA"],
  ["Liechtenstein", "LIE"],
  ["Sri Lanka", "LKA"],
  ["Lesotho", "LSO"],
  ["Lithuania", "LTU"],
  ["Luxembourg", "LUX"],
  ["Latvia", "LVA"],
  ["Macao", "MAC"],
  ["Saint Martin", "MAF"],
  ["Morocco", "MAR"],
  ["Monaco", "MCO"],
  ["Moldova", "MDA"],
  ["Madagascar", "MDG"],
  ["Maldives", "MDV"],
  ["Mexico", "MEX"],
  ["Marshall Islands", "MHL"],
  ["North Macedonia", "MKD"],
  ["Republic of North Macedonia", "MKD"],
  ["Mali", "MLI"],
  ["Malta", "MLT"],
  ["Myanmar", "MMR"],
  ["Montenegro", "MNE"],
  ["Mongolia", "MNG"],
  ["Northern Mariana Islands", "MNP"],
  ["Mozambique", "MOZ"],
  ["Mauritania", "MRT"],
  ["Montserrat", "MSR"],
  ["Martinique", "MTQ"],
  ["Mauritius", "MUS"],
  ["Malawi", "MWI"],
  ["Malaysia", "MYS"],
  ["Mayotte", "MYT"],
  ["Namibia", "NAM"],
  ["New Caledonia", "NCL"],
  ["Niger", "NER"],
  ["Norfolk Island", "NFK"],
  ["Nigeria", "NGA"],
  ["Nicaragua", "NIC"],
  ["Northern Ireland", "NIR"],
  ["N Ireland", "NIR"],
  ["No Ireland", "NIR"],
  ["Niue", "NIU"],
  ["Netherlands", "NLD"],
  ["Norway", "NOR"],
  ["Nepal", "NPL"],
  ["Nauru", "NRU"],
  ["New Zealand", "NZL"],
  ["Oman", "OMN"],
  ["Pakistan", "PAK"],
  ["Panama", "PAN"],
  ["Pitcairn Islands", "PCN"],
  ["Peru", "PER"],
  ["Philippines", "PHL"],
  ["Palau", "PLW"],
  ["Papua New Guinea", "PNG"],
  ["Poland", "POL"],
  ["North Korea", "PRK"],
  ["Democratic People's Republic of Korea", "PRK"],
  ["Portugal", "PRT"],
  ["Prussia", "PRU"],
  ["Paraguay", "PRY"],
  ["Palestine", "PSE"],
  ["Palestinian Territory", "PSE"],
  ["French Polynesia", "PYF"],
  ["Qatar", "QAT"],
  ["Reunion", "REU"],
  ["Romania", "ROU"],
  ["Russia", "RUS"],
  ["Russian Federation", "RUS"],
  ["Rwanda", "RWA"],
  ["Saudi Arabia", "SAU"],
  ["Scotland", "SCT"],
  ["Sudan", "SDN"],
  ["Senegal", "SEN"],
  ["Singapore", "SGP"],
  ["Saint Helena", "SHN"],
  ["Svalbard & Jan Mayen Islands", "SJM"],
  ["Solomon Islands", "SLB"],
  ["Sierra Leone", "SLE"],
  ["El Salvador", "SLV"],
  ["San Marino", "SMR"],
  ["Somalia", "SOM"],
  ["Saint Pierre and Miquelon", "SPM"],
  ["Serbia", "SRB"],
  ["South Sudan", "SSD"],
  ["Sao Tome and Principe", "STP"],
  ["Suriname", "SUR"],
  ["Slovak Republic", "SVK"],
  ["Slovakia", "SVK"],
  ["Slovenia", "SVN"],
  ["Sweden", "SWE"],
  ["Eswatini", "SWZ"],
  ["Swaziland", "SWZ"],
  ["Sint Maarten", "SXM"],
  ["Seychelles", "SYC"],
  ["Syria", "SYR"],
  ["Syrian Arab Republic", "SYR"],
  ["Turks and Caicos Islands", "TCA"],
  ["Chad", "TCD"],
  ["Togo", "TGO"],
  ["Thailand", "THA"],
  ["Tajikistan", "TJK"],
  ["Tokelau", "TKL"],
  ["Turkmenistan", "TKM"],
  ["Timor-Leste", "TLS"],
  ["Kingdom of Tonga", "TON"],
  ["Trinidad and Tobago", "TTO"],
  ["Tunisia", "TUN"],
  ["Turkey", "TUR"],
  ["Tuvalu", "TUV"],
  ["Taiwan", "TWN"],
  ["Tanzania", "TZA"],
  ["Uganda", "UGA"],
  ["United Kingdom", "UK"],
  ["Ukraine", "UKR"],
  ["United States Minor Outlying Islands", "UMI"],
  ["United States Minor Outlying Islands", "UMI"],
  ["Uruguay", "URY"],
  ["United States", "USA"],
  ["United States of America", "USA"],
  ["Uzbekistan", "UZB"],
  ["Holy See", "VAT"],
  ["Vatican City", "VAT"],
  ["Saint Vincent and the Grenadines", "VCT"],
  ["Venezuela", "VEN"],
  ["United States Virgin Islands", "VIR"],
  ["Vietnam", "VNM"],
  ["Vanuatu", "VUT"],
  ["Wallis and Futuna", "WLF"],
  ["Wales", "WLS"],
  ["Samoa", "WSM"],
  ["Yemen", "YEM"],
  ["Yugoslavia", "YUG"],
  ["South Africa", "ZAF"],
  ["Zambia", "ZMB"],
  ["Zimbabwe", "ZWE"],

]
