const it_provices = [

   ["Agrigento", "AG"],
   ["Alessandria", "AL"],
   ["Ancona", "AN"],
   ["Aosta", "AO"],
   ["Arezzo", "AR"],
   ["Ascoli Piceno", "AP"],
   ["Asti", "AT"],
   ["Avellino", "AV"],
   ["Bari", "BA"],
   ["Barletta-Andria-Trani", "BT"],
   ["Belluno", "BL"],
   ["Benevento", "BN"],
   ["Bergamo", "BG"],
   ["Biella", "BI"],
   ["Bologna", "BO"],
   ["Bolzano", "BZ"],
   ["Brescia", "BS"],
   ["Brindisi", "BR"],
   ["Cagliari", "CA"],
   ["Caltanissetta", "CL"],
   ["Campobasso", "CB"],
   ["Carbonia-Iglesias", "CI"],
   ["Caserta", "CE"],
   ["Catania", "CT"],
   ["Catanzaro", "CZ"],
   ["Chieti", "CH"],
   ["Como", "CO"],
   ["Cosenza", "CS"],
   ["Cremona", "CR"],
   ["Crotone", "KR"],
   ["Cuneo", "CN"],
   ["Enna", "EN"],
   ["Fermo", "FM"],
   ["Ferrara", "FE"],
   ["Florence", "FI"],
   ["Foggia", "FG"],
   ["Forlì-Cesena", "FC"],
   ["Frosinone", "FR"],
   ["Genoa", "GE"],
   ["Gorizia", "GO"],
   ["Grosseto", "GR"],
   ["Imperia", "IM"],
   ["Isernia", "IS"],
   ["La Spezia", "SP"],
   ["L'Aquila", "AQ"],
   ["Latina", "LT"],
   ["Lecce", "LE"],
   ["Lecco", "LC"],
   ["Livorno", "LI"],
   ["Lodi", "LO"],
   ["Lucca", "LU"],
   ["Macerata", "MC"],
   ["Mantova", "MN"],
   ["Massa-Carrara", "MS"],
   ["Matera", "MT"],
   ["Medio Campidano", "VS"],
   ["Messina", "ME"],
   ["Milan", "MI"],
   ["Modena", "MO"],
   ["Monza e della Brianza", "MB"],
   ["Naples", "NA"],
   ["Novara", "NO"],
   ["Nuoro", "NU"],
   ["Ogliastra", "OG"],
   ["Olbia-Tempio", "OT"],
   ["Oristano", "OR"],
   ["Padova", "PD"],
   ["Palermo", "PA"],
   ["Parma", "PR"],
   ["Pavia", "PV"],
   ["Perugia", "PG"],
   ["Pesaro e Urbino", "PU"],
   ["Pescara", "PE"],
   ["Piacenza", "PC"],
   ["Pisa", "PI"],
   ["Pistoia", "PT"],
   ["Pordenone", "PN"],
   ["Potenza", "PZ"],
   ["Prato", "PO"],
   ["Ragusa", "RG"],
   ["Ravenna", "RA"],
   ["Reggio Calabria", "RC"],
   ["Reggio Emilia", "RE"],
   ["Rieti", "RI"],
   ["Rimini", "RN"],
   ["Rome", "RM"],
   ["Rovigo", "RO"],
   ["Salerno", "SA"],
   ["Sassari", "SS"],
   ["Savona", "SV"],
   ["Siena", "SI"],
   ["Siracusa", "SR"],
   ["Sondrio", "SO"],
   ["Taranto", "TA"],
   ["Teramo", "TE"],
   ["Terni", "TR"],
   ["Trapani", "TP"],
   ["Trento", "TN"],
   ["Treviso", "TV"],
   ["Trieste", "TS"],
   ["Turin", "TO"],
   ["Udine", "UD"],
   ["Varese", "VA"],
   ["Venice", "VE"],
   ["Verbano-Cusio-Ossola", "VB"],
   ["Vercelli", "VC"],
   ["Verona", "VR"],
   ["Vibo Valentia", "VV"],
   ["Vicenza", "VI"],
   ["Viterbo", "VT"],

];