const us_states = [

   ["Alabama", "AL"],
   ["Alaska", "AK"],
   ["American Samoa", "AS"],
   ["Arizona", "AZ"],
   ["Arkansas", "AR"],
   ["California", "CA"],
   ["Colorado", "CO"],
   ["Connecticut", "CT"],
   ["Delaware", "DE"],
   ["District Of Columbia", "DC"],
   ["Florida", "FL"],
   ["Georgia", "GA"],
   ["Guam", "GU"],
   ["Hawaii", "HI"],
   ["Idaho", "ID"],
   ["Illinois", "IL"],
   ["Indiana", "IN"],
   ["Iowa", "IA"],
   ["Kansas", "KS"],
   ["Kentucky", "KY"],
   ["Louisiana", "LA"],
   ["Maine", "ME"],
   ["Marshall Islands", "MH"],
   ["Maryland", "MD"],
   ["Massachusetts", "MA"],
   ["Michigan", "MI"],
   ["Minnesota", "MN"],
   ["Mississippi", "MS"],
   ["Missouri", "MO"],
   ["Montana", "MT"],
   ["Nebraska", "NE"],
   ["Nevada", "NV"],
   ["New Hampshire", "NH"],
   ["New Jersey", "NJ"],
   ["New Mexico", "NM"],
   ["New York", "NY"],
   ["North Carolina", "NC"],
   ["North Dakota", "ND"],
   ["Northern Mariana Islands", "NP"],
   ["Ohio", "OH"],
   ["Oklahoma", "OK"],
   ["Oregon", "OR"],
   ["Pennsylvania", "PA"],
   ["Puerto Rico", "PR"],
   ["Rhode Island", "RI"],
   ["South Carolina", "SC"],
   ["South Dakota", "SD"],
   ["Tennessee", "TN"],
   ["Texas", "TX"],
   ["US Virgin Islands", "VI"],
   ["Utah", "UT"],
   ["Vermont", "VT"],
   ["Virginia", "VA"],
   ["Washington", "WA"],
   ["West Virginia", "WV"],
   ["Wisconsin", "WI"],
   ["Wyoming", "WY"],

   // Non-standard
   ["Ala", "AL"],
   ["Ark", "AR"],
   ["Ariz", "AZ"],
   ["Calif", "CA"],
   ["Cal", "CA"],
   ["Colo", "CO"],
   ["Col", "CO"],
   ["Conn", "CT"],
   ["Del", "DE"],
   ["Fla", "FL"],
   ["Flor", "FL"],
   ["Ga", "GA"],
   ["Ida", "ID"],
   ["Ill", "IL"],
   ["Ind", "IN"],
   ["Kans", "KS"],
   ["Kan", "KS"],
   ["Ken", "KY"],
   ["Kent", "KY"],
   ["Mass", "MA"],
   ["Mich", "MI"],
   ["Minn", "MN"],
   ["Miss", "MS"],
   ["Mont", "MT"],
   ["N Dak", "ND"],
   ["Nebr", "NE"],
   ["Neb", "NE"],
   ["N Mex", "NM"],
   ["Nev", "NV"],
   ["Okla", "OK"],
   ["Ore", "OR"],
   ["Penn", "PA"],
   ["Penna", "PA"],
   ["S Dak", "SD"],
   ["Tenn", "TN"],
   ["Tex", "TX"],
   ["Wash", "WA"],
   ["Wis", "WI"],
   ["W Va", "WV"],
   ["Wisc", "WY"],
   ["Wyo", "WY"],

];
